// The legacy 7 ceremony categories as configurable award definitions.
// Inserted once when award_defs is empty; from then on the admin UI owns them.
// IDs must match weeklyAwards.ts so the parity test can compare winners.

import type { AwardDef } from "./types";

const base = {
  window: "campaign" as const,
  tieBreakers: [] as AwardDef["tieBreakers"],
  eligibility: {},
  prizes: [] as AwardDef["prizes"],
  status: "active" as const,
};

export const SEED_AWARD_DEFS: AwardDef[] = [
  { ...base, id: "biggest-jump", name: "Biggest Weekly Jump",
    subtitle: "Largest Sunday attendance gain in the past week", emoji: "🚀", tone: "teal",
    evaluator: "metric_rank", metricId: "weekly_jump", scope: { type: "all" }, tiers: 1,
    window: "latest-week", eligibility: { requirePositive: true }, sort: 10,
    blurb: "Something is moving here — whatever they did last week, do it again." },
  { ...base, id: "full-house", name: "Full House",
    subtitle: "Highest single-Sunday worship attendance", emoji: "🏠", tone: "blue",
    evaluator: "metric_rank", metricId: "sunday_peak", scope: { type: "all" }, tiers: 1,
    eligibility: { requirePositive: true }, sort: 20,
    blurb: "The room was packed. That is what momentum looks like." },
  { ...base, id: "treasury", name: "Treasury Titans",
    subtitle: "Top 3 in income growth this trimester", emoji: "💰", tone: "gold",
    evaluator: "metric_rank", metricId: "finance_points", scope: { type: "all" }, tiers: 3, sort: 30,
    blurb: "Generosity is leadership. These communities grew their giving the most." },
  { ...base, id: "gatherers", name: "Gatherers of People",
    subtitle: "Top 3 in active membership growth", emoji: "🧑‍🤝‍🧑", tone: "teal",
    evaluator: "metric_rank", metricId: "member_points", scope: { type: "all" }, tiers: 3, sort: 40,
    blurb: "Real people, actually participating. The heart of the whole game." },
  { ...base, id: "blessing", name: "Blessing Pipeline",
    subtitle: "Top 3 moving people through the Blessing journey", emoji: "💞", tone: "rose",
    evaluator: "metric_rank", metricId: "blessing_points", scope: { type: "all" }, tiers: 3, sort: 50,
    blurb: "Step by step — credit for the movement, not just the ceremony." },
  { ...base, id: "size-xlm", name: "XLM Champion",
    subtitle: "Best XLM community by total points", emoji: "🐘", tone: "violet",
    evaluator: "metric_rank", metricId: "total_points",
    scope: { type: "size", sizes: ["Extra Large", "Medium"] }, tiers: 1, sort: 60,
    blurb: "Leading the division and setting the pace." },
  { ...base, id: "size-small", name: "Small Champion",
    subtitle: "Best Small community by total points", emoji: "🐢", tone: "violet",
    evaluator: "metric_rank", metricId: "total_points",
    scope: { type: "size", sizes: ["Small"] }, tiers: 1, sort: 70,
    blurb: "Punching above their weight — growth is measured from your own baseline." },
  { ...base, id: "size-family-group", name: "Family Group Champion",
    subtitle: "Best Family Group community by total points", emoji: "🐣", tone: "violet",
    evaluator: "metric_rank", metricId: "total_points",
    scope: { type: "size", sizes: ["Family Group"] }, tiers: 1, sort: 80,
    blurb: "Punching above their weight — growth is measured from your own baseline." },
  { ...base, id: "david", name: "The David Award",
    subtitle: "A small community out-pointing the giants", emoji: "🪨", tone: "gold",
    evaluator: "david", scope: { type: "all" }, tiers: 1, sort: 90,
    blurb: "Size is not destiny. Baselines are. Well done." },
  { ...base, id: "triple-header", name: "Triple-Header Honors",
    subtitle: "Beat target in Income, Members, AND Blessing", emoji: "⭐", tone: "gold",
    evaluator: "triple_header", scope: { type: "all" }, tiers: 1, sort: 100,
    blurb: "The rarest feat in the campaign. Standing ovation." },
  { ...base, id: "league-champion", name: "League Champion",
    subtitle: "Overall #1 — most total points this trimester", emoji: "👑", tone: "gold",
    evaluator: "metric_rank", metricId: "total_points", scope: { type: "all" }, tiers: 3, sort: 110,
    blurb: "Top of the standings. The score is a mirror of the mission — and the mission is winning." },
];
