/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AwardsAdminRouteImport } from './routes/awards_.admin'

const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsAdminRoute = AwardsAdminRouteImport.update({
  id: '/awards_/admin',
  path: '/awards/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/dashboard': typeof DashboardRoute
  '/scoreboard': typeof ScoreboardRoute
  '/awards/admin': typeof AwardsAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/dashboard': typeof DashboardRoute
  '/scoreboard': typeof ScoreboardRoute
  '/awards/admin': typeof AwardsAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/dashboard': typeof DashboardRoute
  '/scoreboard': typeof ScoreboardRoute
  '/awards_/admin': typeof AwardsAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/awards' | '/dashboard' | '/scoreboard' | '/awards/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/awards' | '/dashboard' | '/scoreboard' | '/awards/admin'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/dashboard'
    | '/scoreboard'
    | '/awards_/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  DashboardRoute: typeof DashboardRoute
  ScoreboardRoute: typeof ScoreboardRoute
  AwardsAdminRoute: typeof AwardsAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards_/admin': {
      id: '/awards_/admin'
      path: '/awards/admin'
      fullPath: '/awards/admin'
      preLoaderRoute: typeof AwardsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  DashboardRoute: DashboardRoute,
  ScoreboardRoute: ScoreboardRoute,
  AwardsAdminRoute: AwardsAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
